CREATE TABLE perfil (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    nome_perfil VARCHAR(120) NOT NULL,
    avatar_url VARCHAR(500),
    tipo_perfil VARCHAR(20) NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_perfil_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id),
    CONSTRAINT ck_perfil_tipo CHECK (tipo_perfil IN ('ADULTO', 'INFANTIL'))
);
