CREATE TABLE filme (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(200) NOT NULL,
    sinopse TEXT,
    ano_lancamento INTEGER NOT NULL,
    duracao_min INTEGER NOT NULL,
    classificacao_indicativa VARCHAR(20) NOT NULL,
    poster_url VARCHAR(500)
);
